# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 10000

format = '''$character $directory$git_branch$git_status$nodejs'''

[character]
success_symbol = '[󰆧](bold green)'
error_symbol = '[󰆧](bold red)'

[directory]
truncation_length = 1

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[nodejs]
format = "[$symbol($version )]($style)"
